"""Small-talk router: the conversational layer in front of the retrieval pipeline.

Without it, "hi" runs the whole machine -- an embedding call, a hybrid search, RRF,
confidence tiering, then an LLM relevance verdict -- only to come back with
guardrail.py's off-topic template ("This looks like it's about project details, which
is out of scope for UAE health regulation..."). That is the wrong register for a
greeting and it isn't free. This module answers those inputs at the very top of both
entry points: zero embeddings, zero LLM calls, zero DB reads, and nothing enters the
answer cache.

**Deterministic only -- no model call decides anything here.** Two guards make a false
positive on a real regulation question essentially impossible:

1. *Whole-string anchored match.* The input is normalized (lowercased, punctuation and
   diacritics stripped, whitespace collapsed) and then the ENTIRE normalized string
   must equal a known phrase. "hi" routes; "hi, what are the DHA licensing fees?" does
   not, and falls through to the real pipeline untouched.
2. *Word ceiling.* Anything over MAX_SMALLTALK_WORDS words is never even considered.

Every response is a fixed string, never model prose -- the same discipline
guardrail.py already uses for build_offtopic_message()/validate_redirect(). The one
response that varies, `model`, is composed at call time from the actual configured
model constants so it can never drift from what the app really runs.
"""
from __future__ import annotations

import re
import unicodedata

# An input longer than this is a question, not a pleasantry -- checked before any
# phrase lookup, so a long input can never route no matter what it contains.
MAX_SMALLTALK_WORDS = 8

# Curated, static, and deliberately tiny: small talk has no query vector, so
# services.suggestions.find_suggested_followups() (which cosine-matches against the
# mined table) has nothing to match on. These three are the same starters the empty
# state offers -- one per authority, all known-answerable from the corpus.
DEFAULT_STARTERS = [
    "What are the requirements for licensing a healthcare professional in Dubai?",
    "What is the structure of Abu Dhabi health regulations?",
    "Which emirates does MOHAP directly regulate as the federal health authority?",
]


def _model_response() -> str:
    """Composed from the real constants, never a literal, so this answer cannot go
    stale when the chain changes. Imported at call time: retrieval imports this
    module, so a top-level import back would be circular (the same deferred-import
    shape guardrail.check_relevance uses)."""
    from app.core.retrieval import (
        CHAT_MODEL,
        DEFAULT_LOCAL_MODEL,
        EMBED_MODEL,
        NARAROUTER_MODEL,
    )

    return (
        f"Answers are generated by OpenAI's {CHAT_MODEL} by default. If OpenAI is "
        f"unavailable or rate-limited, generation falls back automatically to "
        f"{NARAROUTER_MODEL} via NaraRouter, and you can switch generation to a local "
        f"model instead ({DEFAULT_LOCAL_MODEL} by default) running in LM Studio. "
        f"Retrieval always uses OpenAI's {EMBED_MODEL} embeddings. Whichever model "
        "answers, it doesn't supply the facts -- the answer is built from retrieved "
        "regulation text and cited back to the document, version and page."
    )


# intent -> phrases (matched against the WHOLE normalized input), fixed response text
# (a str, or a callable composing it from config), and starter chips.
INTENTS: dict[str, dict] = {
    "greeting": {
        "phrases": [
            "hi", "hii", "hiii", "hello", "helo", "hey", "heya", "hiya", "hi there",
            "hey there", "hello there", "good morning", "good afternoon",
            "good evening", "good day", "greetings", "yo", "hola", "howdy", "sup",
            "whats up", "what s up", "wassup",
            "salam", "salaam", "salam alaikum", "assalamu alaikum",
            "assalam alaikum", "as salamu alaykum", "marhaba", "marhaban", "ahlan",
            "ahlan wa sahlan", "hi regulense", "hello regulense",
            "how are you", "how are you doing", "hows it going", "how s it going",
            "how is it going", "hows things", "how s things", "how you doing",
            "hi how are you", "hello how are you", "hey how are you",
            "مرحبا", "أهلا",
            "السلام عليكم",
        ],
        "response": (
            "Hello. I'm ReguLense -- I answer questions about UAE health regulation "
            "from Dubai Health Authority, Department of Health Abu Dhabi and MOHAP "
            "source documents, and every answer cites the document, version and page "
            "it came from. What requirement would you like to check?"
        ),
        "starters": DEFAULT_STARTERS,
    },
    "thanks": {
        "phrases": [
            "thanks", "thank you", "thank u", "thanks a lot", "thanks alot",
            "thanks so much", "thank you very much", "thank you so much",
            "many thanks", "much appreciated", "appreciated", "thx", "ty", "cheers",
            "shukran", "shukran jazeelan",
            "شكرا",
        ],
        "response": (
            "You're welcome. If anything else comes up on DHA, DoH or MOHAP "
            "requirements, just ask."
        ),
        "starters": DEFAULT_STARTERS,
    },
    "farewell": {
        "phrases": [
            "bye", "bye bye", "goodbye", "good bye", "see you", "see ya",
            "see you later", "farewell", "take care", "good night", "goodnight",
            "maa salama", "ma salama",
        ],
        "response": (
            "Goodbye. Come back any time you need a requirement checked against the "
            "source document."
        ),
        "starters": DEFAULT_STARTERS,
    },
    "about": {
        "phrases": [
            "what is this", "what is this app", "what is this site",
            "what is this tool", "what is this for", "what is this about",
            "whats this", "whats this app", "what is regulense", "whats regulense",
            "what does this do", "what do you do", "what can you do",
            "tell me about this", "tell me about regulense", "about",
        ],
        "response": (
            "ReguLense is a regulation-checking tool for clinicians, compliance "
            "officers and hospital administrators working under UAE health "
            "regulation (DHA, DoH Abu Dhabi and MOHAP). It searches the actual "
            "published regulation documents, tracks which version of a regulation is "
            "in force and which has been superseded, and cites the document, version "
            "and page behind every statement. When the corpus doesn't support an "
            "answer, it says so instead of guessing."
        ),
        "starters": DEFAULT_STARTERS,
    },
    "capability": {
        "phrases": [
            "what can you answer", "what can you help with",
            "what can you help me with", "what topics", "what topics do you cover",
            "what do you cover", "which topics do you cover",
            "what areas do you cover", "what questions can you answer",
            "what can i ask", "what can i ask you", "what do you know",
            "what documents do you have", "what is in your corpus",
        ],
        "response": (
            "I cover UAE health regulation from three authorities: the Dubai Health "
            "Authority, the Department of Health - Abu Dhabi, and the Ministry of "
            "Health and Prevention. Typical ground: professional and facility "
            "licensing, scopes of practice, staffing and qualification requirements, "
            "telehealth standards, clinical and patient-safety standards, health data "
            "and reporting, inspections, fees and timelines -- the obligations a "
            "practitioner, facility or health office actually has to meet. Ask in "
            "plain English and you'll get the answer with its source."
        ),
        "starters": DEFAULT_STARTERS,
    },
    "model": {
        "phrases": [
            "what model are you", "which model are you", "what model are you using",
            "which model are you using", "what model do you use",
            "which model do you use", "what model is this", "what llm", "which llm",
            "what llm are you", "which llm are you", "what llm do you use",
            "are you chatgpt", "are you gpt", "are you gpt 4", "are you claude",
            "are you openai", "are you an ai", "what ai are you", "which ai are you",
            "what are you built on", "what powers you",
        ],
        "response": _model_response,
        "starters": DEFAULT_STARTERS,
    },
    "help": {
        "phrases": [
            "help", "help me", "i need help", "can you help", "can you help me",
            "how do i use this", "how do i use it", "how to use this",
            "how does this work", "how does it work", "how do i start",
            "how do i get started", "get started", "how do i ask a question",
        ],
        "response": (
            "Type a question about UAE health regulation in plain English -- for "
            "example \"How long is a DHA professional licence valid?\". You get a "
            "short answer with the exact document, version and page behind it, and "
            "you can open the cited page of the PDF with the passage highlighted. "
            "The filters let you include or exclude superseded versions and limit "
            "answers to one authority. If the corpus doesn't support an answer, I "
            "abstain rather than guess."
        ),
        "starters": DEFAULT_STARTERS,
    },
    "identity": {
        "phrases": [
            "who are you", "who made you", "who built you", "who created you",
            "who built this", "who created this", "who made this",
            "who developed this", "who is behind this", "who owns this",
            "what is your name", "whats your name",
        ],
        "response": (
            "I'm ReguLense, a compliance research assistant used by clinicians and "
            "hospital officials to check UAE health regulation. I'm not a person and "
            "not a regulator -- I retrieve and quote published DHA, DoH Abu Dhabi and "
            "MOHAP documents, with the version and page cited so you can verify every "
            "claim against the source yourself before you act on it."
        ),
        "starters": DEFAULT_STARTERS,
    },
    "affirmation": {
        "phrases": [
            "ok", "okay", "k", "kk", "cool", "nice", "great", "awesome", "got it",
            "understood", "i see", "makes sense", "alright", "sure", "perfect",
            "no problem", "np", "yeah", "yep", "indeed", "fair enough",
        ],
        "response": (
            "Got it. Ask whenever you're ready -- anything on DHA, DoH or MOHAP "
            "regulation."
        ),
        "starters": DEFAULT_STARTERS,
    },
}


def normalize(text: str) -> str:
    """Lowercase, strip diacritics, drop punctuation, collapse whitespace. NFKD plus
    combining-mark removal handles both Latin accents and Arabic harakat, so
    "أهلاً" and "اهلا" normalize to the
    same string."""
    decomposed = unicodedata.normalize("NFKD", text or "")
    stripped = "".join(ch for ch in decomposed if not unicodedata.combining(ch))
    lowered = stripped.lower()
    # \w keeps letters (any script) and digits; everything else becomes a space, so
    # trailing "!", "?" and "..." can't stop a phrase from matching.
    words = re.sub(r"[^\w\s]|_", " ", lowered)
    return re.sub(r"\s+", " ", words).strip()


# Built once at import: normalized phrase -> intent. A phrase appearing under two
# intents would silently shadow, so the build asserts uniqueness rather than letting
# dict order decide.
_INTENT_BY_PHRASE: dict[str, str] = {}
for _intent, _spec in INTENTS.items():
    for _phrase in _spec["phrases"]:
        _key = normalize(_phrase)
        if _key in _INTENT_BY_PHRASE:
            raise ValueError(
                f"small-talk phrase {_key!r} is claimed by both "
                f"{_INTENT_BY_PHRASE[_key]!r} and {_intent!r}"
            )
        _INTENT_BY_PHRASE[_key] = _intent


def response_for(intent: str) -> str:
    """The fixed text for an intent; `model`'s is composed from config at call time."""
    response = INTENTS[intent]["response"]
    return response() if callable(response) else response


def match_intent(question: str) -> str | None:
    """The whole matcher: normalize, refuse anything over the word ceiling, then look
    up the entire normalized string. Exposed separately from route() so tests (and any
    future caller) can assert routing decisions without building a result dict."""
    normalized = normalize(question)
    if not normalized:
        return None
    if len(normalized.split()) > MAX_SMALLTALK_WORDS:
        return None
    return _INTENT_BY_PHRASE.get(normalized)


def route(question: str) -> dict | None:
    """Returns a ready-to-serve abstention dict for small talk, or None to let the
    real pipeline handle the input.

    The shape mirrors the existing off-topic abstention (see retrieval.py's guardrail
    branch) so app/api/routers/ can keep passing the dict straight through as JSON:
    `smalltalk` and `intent` are additive flags, and `suggested_followups` uses the
    same {"question": ...} element shape the mined suggestions use, so the frontend
    renders them through the same FollowUpQuestions component. `run_id` is attached by
    the caller, which owns the trace."""
    intent = match_intent(question)
    if intent is None:
        return None
    return {
        "abstained": True,
        "smalltalk": True,
        "intent": intent,
        "reason": response_for(intent),
        "suggested_followups": [{"question": q} for q in INTENTS[intent]["starters"]],
    }
